import React from 'react';
import './TroubleshootingFixDiffView.css';

// Small LCS-based line diff - files here are capped to a few thousand
// characters (fetched/generated by the backend with the same cap), so a
// plain O(n*m) DP table is more than fast enough.
function computeLineDiff(oldText, newText) {
  const a = (oldText || '').split('\n');
  const b = (newText || '').split('\n');
  const n = a.length;
  const m = b.length;

  const dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));
  for (let i = n - 1; i >= 0; i -= 1) {
    for (let j = m - 1; j >= 0; j -= 1) {
      dp[i][j] = a[i] === b[j] ? dp[i + 1][j + 1] + 1 : Math.max(dp[i + 1][j], dp[i][j + 1]);
    }
  }

  const rows = [];
  let i = 0;
  let j = 0;
  while (i < n && j < m) {
    if (a[i] === b[j]) {
      rows.push({ type: 'unchanged', line: a[i] });
      i += 1;
      j += 1;
    } else if (dp[i + 1][j] >= dp[i][j + 1]) {
      rows.push({ type: 'removed', line: a[i] });
      i += 1;
    } else {
      rows.push({ type: 'added', line: b[j] });
      j += 1;
    }
  }
  while (i < n) {
    rows.push({ type: 'removed', line: a[i] });
    i += 1;
  }
  while (j < m) {
    rows.push({ type: 'added', line: b[j] });
    j += 1;
  }
  return rows;
}

function FileDiff({ path, oldContent, newContent }) {
  const rows = computeLineDiff(oldContent, newContent);
  return (
    <div className="tfd-file">
      <div className="tfd-file-path font-mono">{path}</div>
      <div className="tfd-diff-lines">
        {rows.map((row, idx) => (
          <div key={idx} className={`tfd-line tfd-line-${row.type}`}>
            <span className="tfd-line-marker">{row.type === 'added' ? '+' : row.type === 'removed' ? '-' : ' '}</span>
            <span className="tfd-line-text">{row.line}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function TroubleshootingFixDiffView({ proposedFix, onApprove, onCancel, approving }) {
  return (
    <div className="tfd-wrapper">
      <div className="tfd-header">
        <h3 className="tfd-title">Proposed Code Fix</h3>
        <span className="tfd-warning">Nothing has been pushed yet - review before approving.</span>
      </div>

      <div className="tfd-commit-message font-mono">{proposedFix.commitMessage}</div>

      {proposedFix.files.map((f) => (
        <FileDiff key={f.path} path={f.path} oldContent={f.oldContent} newContent={f.newContent} />
      ))}

      <div className="tfd-actions">
        <button type="button" className="tfd-approve-btn" disabled={approving} onClick={onApprove}>
          {approving ? 'Pushing...' : 'Approve & Push'}
        </button>
        <button type="button" className="tfd-cancel-btn" disabled={approving} onClick={onCancel}>
          Cancel
        </button>
      </div>

      <p className="tfd-note">
        Approving will commit and push this change to your repository's default branch and redeploy - automatically retrying up to the
        remaining attempt limit if it doesn't resolve the failure.
      </p>
    </div>
  );
}

export default TroubleshootingFixDiffView;
